name: BNes
main: cn.whiteg.bnes.BNes
version: 1.3.5
api-version: 1.17
author: MoeWhite
depend: [ ]
softdepend: [ Vault , voicechat]
commands:
  bnes:
    description: The is BNes Command
    aliases: [ 'nes','ns' ]
